lib/screens/githostsetup_clone_url.dart

fixed git-clone-url-regex for dash-domains

---

lib/screens/journal_editor.dart

[Feat] add FAB for note saving

---

BUILD.md
CONTRIBUTING.md
android/app/build.gradle

Also tune up build.gradle for handling non existing key.properties file:
Simplify local dev with no signing keys.

[Feat] add contributing and more build instructions

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/PULL_REQUEST_TEMPLATE.md

Add templates to create new issues and pull requests

Add issue and pr templates

---

BUILD.md

Nothing to exciting here, but wanted to do my part to keep this great App in tip-top shape! 🔝 🥇😉
Just some small clean ups to the BUILD.md notes.

few spelling corrections in BUILD.md

---

BUILD.md
android/app/build.gradle

- Added trouble shooting advise for "Build fails on project `git_bindings` with a 'NullPointerException'".
- Local build now works with encrypted `key.properties` present
Local build with both encrypted and unencrypted `key.properties` file should work.

Better Contributing Experience

---

assets/langs/es.yaml

Hi!
I translated the app strings to Spanish. I hope that offering to choose the language in the app will be easy :blush:

Spanish translation

---

assets/langs/pl.yaml

polish lang

---

android/app/src/main/AndroidManifest.xml
pubspec.yaml

Resolve issue  #377
Connected to #428
Can confirm in the emulator.

#428 fixing the permissions

---

assets/langs/en.yaml
lib/app_settings.dart
lib/screens/folder_listing.dart
lib/screens/settings_experimental.dart

Resolve issue #429 
I added the setting to the Experimental features.
Please do provide some feedback. I'm still learning!

include subfolders feature

---

assets/langs/en.yaml
assets/langs/es.yaml
assets/langs/pl.yaml
lib/screens/settings_display_images.dart
lib/screens/settings_display_images_caption.dart
lib/screens/settings_display_images_theming.dart
lib/screens/settings_screen.dart
lib/settings.dart
lib/utils/hero_dialog.dart
lib/widgets/image_renderer.dart
lib/widgets/markdown_renderer.dart
pubspec.lock
pubspec.yaml

Closes #405 
Improves #410
Closes #246 
- SVGs should render correctly ([There are some things not working](https://github.com/dnfield/flutter_svg/issues))
- Theming:
- By default SVGs with background and raster graphics should not be themed 
- Overrides should work in both altText and Tooltip
- Background detection works on checking if there is any path containing all 4 corners, this may result in false positives
- You can choose which colors should be changed: `all`, `grays`, `black and white`
White is adjusted to match Background:
All Colors are themed:
Brightness of Saturated Colors is not changed:

SVG Rendering, Image theming and Image caption

---

lib/core/git_repo.dart

Hopefully it will provide more context to debug recent sync issue.
Connected to #361

Put current branch name in exception

---

BUILD.md
android/build.gradle

instructions + gradle version

---

lib/core/note.dart
lib/screens/note_editor.dart
lib/utils/link_resolver.dart
lib/widgets/note_editor_selector.dart

Resolve issue #463
Connected to #145 
Initial support for existing .org files in the repository. Required in order to apply search to existing files.
The work will continue but I would like to have smaller chunks implemented rather than a big-bang neverending story.

initial support for .org files

---

lib/editors/scaffold.dart
pubspec.lock
pubspec.yaml

initial org viewer

---

lib/core/org_links_handler.dart
lib/editors/scaffold.dart

Image viewer for image links in .org files.

image viewer for .org files

---

lib/editors/scaffold.dart

listing available event handlers

---

README.md

I had successfully migrated my notes to GitJournal format using this simple hand-made tool written in Go.
Also, I'd like to thank you a lot for the application you've created, can't wait to see web version (and it is perfectly fine for me if it will be paid in some way).

Add link to Simplenote exporter

---

pubspec.lock
pubspec.yaml

Just a minor update. No effective changes.
Smoke test performed locally.

updating org_flutter

---

assets/langs/ja.yaml
ios/Runner/Info.plist
lib/app.dart

Resolve issue #504 
As GitJournalApp says for me in twitter, I made Japanese locale resource and added localizations to app.
This is my first PR ever. If there're any mistakes, please feel free to tell me.

Add Japanese Localization

---

lib/widgets/app_drawer.dart

Fix theme style not applied to repo tile in drawer
